### ISSUE TITLE
Seems to not work, if compiled under 7.6.4

### ISSUE THREAD

**Issue by wuuemm** [tjkaal/ResetButtonForTextField#10]
If compiled under 7.6.4, the old problem returns: Hierarchy claims TexField contains components.

**Comment by tjkaal** [comment]
I just tested this by updating the demo app to 7.6.4 and it works fine. Could you create an example project that demonstrates the issue?

**Comment by wuuemm** [comment]
I must have made some mistake I can't currently reproduce. You're right, it works. Sorry for trouble.

**Comment by tapioaali** [comment]
Great!
