### ISSUE TITLE
Icon for reset

### ISSUE THREAD

**Issue by agent207** [tjkaal/ResetButtonForTextField#7]
I can't seem to get the icon for reset to appear on the right within the textfield when I begin to type.

**Comment by tjkaal** [comment]
Could you attach an example UI? Can't do anything with this info.

**Comment by agent207** [comment]
Question, do I need to add @VaadinServletConfiguration for widgetset = "org.vaadin.resetbuttonfortextfield.DemoWidgetSet"

**Comment by tjkaal** [comment]
If you have named your widgetset like that
